In [5]:
import joblib

In [1]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-mpnet-base-v2', device='cpu')


/home/tpavic/code/RAG-Movies/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
sentences = ["Spider-man movie fighting Green Goblin", "Titanic hits the iceberg.", "Spider-man was a friend with ironman against captain america."]
embeddings = model.encode(sentences)

In [3]:
similarities = model.similarity(embeddings, embeddings)
print(similarities)

tensor([[1.0000, 0.1378, 0.4409],
        [0.1378, 1.0000, 0.0788],
        [0.4409, 0.0788, 1.0000]])


In [7]:
joblib.dump(embeddings, 'embeddings.joblib')

['embeddings.joblib']

In [6]:
loaded_embeddings = joblib.load('embeddings.joblib')

print(loaded_embeddings.shape)  

(2, 768)


In [8]:
type(loaded_embeddings)

numpy.ndarray

In [9]:
similarities = model.similarity(loaded_embeddings, loaded_embeddings)
print(similarities)

tensor([[1.0000, 0.7652],
        [0.7652, 1.0000]])


In [4]:
embeddings

array([[ 0.02164115,  0.02159123,  0.00214396, ..., -0.06094076,
        -0.00284813,  0.00483995],
       [ 0.0027666 ,  0.01626474, -0.00406806, ..., -0.04357989,
         0.04805489, -0.02605465]], shape=(2, 768), dtype=float32)

In [2]:
model.device

device(type='cuda', index=0)

In [ ]:
rrf_scores = {}

for beta, ranked_list in zip(betas, ranked_lists):
    for rank, doc_id in enumerate(ranked_list, start=1):  # ranks start at 1
        rrf_scores[doc_id] = rrf_scores.get(doc_id, 0) + beta * (1 / (K + rank))

# Sort by descending score
sorted_items = sorted(rrf_scores, key=rrf_scores.get, reverse=True)

return sorted_items[:top_k]

In [1]:
rrf_scores = {}

for lst in [[20, 10, 40], [40, 50, 20]]:
    # Calculate the RRF score for each document index
    for rank, item in enumerate(lst, start=1): # Start = 1 set the first element as 1 and not 0. 
                                                # This is a convention on how ranks work (the first element in ranking is denoted by 1 and not 0 as in lists)
        # If the item is not in the dictionary, initialize its score to 0
        if item not in rrf_scores:
            rrf_scores[item] = 0
        # Update the RRF score for each document index using the formula 1 / (rank + K)
        rrf_scores[item] += 1 / (K + rank)

# Sort the document indices based on their RRF scores in descending order
sorted_items = sorted(rrf_scores, key=rrf_scores.get, reverse = True)

# Slice the list to get the top-k document indices
top_k_indices = [int(x) for x in sorted_items]

### END CODE HERE ###

return top_k_indices[:top_k]

NameError: name 'K' is not defined